### ISSUE TITLE
Integration of Leaflet with Angualr4 

### ISSUE THREAD

**Issue by PrarabdhJoshi** [PrarabdhJoshi/map-builer#1]
We are currently using Google Maps to display the map UI on the home page. This needs to be changed to leaflet though but currently it is not being rendered.

**Comment by BharathAlva** [comment]
Leaflet continues to have rendering problem. Looking into this issue.

**Comment by BharathAlva** [comment]
Switching to Google Maps. Chosen as it satisfies the requirement and Leaflet continues to cause problems.
