### ISSUE TITLE
Error Connecting to API

### ISSUE THREAD

**Issue by PrarabdhJoshi** [PrarabdhJoshi/map-builer#17]
@BharathAlva Please check the following error that Angular produces on making a http get request using HttpClient module

**No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.**

**Comment by BharathAlva** [comment]
Trying to resolve this. Looking into it

**Comment by PrarabdhJoshi** [comment]
I have been handling this wrong. It was a dependency issue from the server side. Resolved now.
