### ISSUE TITLE
Finding a suitable Angular Material Design 

### ISSUE THREAD

**Issue by PrarabdhJoshi** [PrarabdhJoshi/map-builer#2]
build a suitable Angular Material Design for the Search Based UI like ours.

**Comment by PrarabdhJoshi** [comment]
@BharathAlva This is the kind of template we would require:
![image](https://user-images.githubusercontent.com/27039880/31461842-ae53adf2-ae98-11e7-9a04-fe6b53808e6a.png)

**Comment by BharathAlva** [comment]
Material Design Template done. Search is still an Problem . That is raised in another issue
