### ISSUE TITLE
Front End TASK

### ISSUE THREAD

**Issue by PrarabdhJoshi** [PrarabdhJoshi/map-builer#8]
@BharathAlva  Please implement Angular Google Map and run a ng-for loop over dummy data to show pins on the map. 
2. bind clickable events to the pins opening a Card window(Angular Material), listing venue details. 
3. Make API requests and replace dummy data with our API data once implemented. 
Extended Goal> Implement autocomplete and Full Text Search Feature on this dummy data.

**Comment by BharathAlva** [comment]
map window and pins are implemented

**Comment by BharathAlva** [comment]
Please take a look at API implementation.

**Comment by BharathAlva** [comment]
Dummy data implemented and component is functioning properly
